/*
 * AddWarehouseRequestDto
 *
 * This DTO (Data Transfer Object) is used to receive data from the client
 * when creating a new Warehouse record.
 *
 * API Usage:
 * - Triggered when client calls:
 *   POST /api/v1/warehouses
 *
 * Purpose:
 * - Transfers warehouse data from the client layer (Frontend/Postman)
 *   to the Controller and Service layer.
 * - Prevents exposing the Warehouse entity directly.
 *
 * Included Fields:
 * - name
 * - companyId
 * - email
 * - phone
 * - status
 * - address
 *
 * Excluded Fields:
 * - id (auto-generated by database)
 * - createdDate (system-managed)
 * - updatedDate (system-managed)
 * - createdBy / updatedBy (system-managed)
 */

package inventorymanagement.warehouse_service.dto;

import jakarta.validation.constraints.*;

public class WarehouseRequestDto {

    @NotBlank(message = "Warehouse name is required")
    private String name;

    @NotNull(message = "Company ID is required")
    private Integer companyId;

    @Email(message = "Email must be a valid email address")
    @Size(max = 100, message = "Email cannot exceed 100 characters")
    private String email;

    @Size(max = 20, message = "Phone cannot exceed 20 characters")
    private String phone;

    @NotBlank(message = "Status is required")
    @Size(max = 50, message = "Status cannot exceed 50 characters")
    private String status;

    @Size(max = 255, message = "Address cannot exceed 255 characters")
    private String address;

    public WarehouseRequestDto() {
    }

    public WarehouseRequestDto(String name, Integer companyId, String email,
                                  String phone, String status, String address) {
        this.name = name;
        this.companyId = companyId;
        this.email = email;
        this.phone = phone;
        this.status = status;
        this.address = address;
    }

    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }

    public Integer getCompanyId() {
        return companyId;
    }
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public String getEmail() {
        return email;
    }
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    public String getAddress() {
        return address;
    }
    public void setAddress(String address) {
        this.address = address;
    }
}