#!/bin/sh

# Generate runtime env config from environment variables
cat <<EOF > /usr/share/nginx/html/env-config.js
window._env_ = {
  VITE_USER_SERVICE: "${VITE_USER_SERVICE}",
  VITE_PRODUCT_SERVICE: "${VITE_PRODUCT_SERVICE}",
  VITE_PO_SERVICE: "${VITE_PO_SERVICE}",
  VITE_MAINTENANCE_SERVICE: "${VITE_MAINTENANCE_SERVICE}",
  VITE_COMPANY_SERVICE: "${VITE_COMPANY_SERVICE}",
  VITE_STOCK_SERVICE: "${VITE_STOCK_SERVICE}",
  VITE_STOCK_TRANSFER_SERVICE: "${VITE_STOCK_TRANSFER_SERVICE}",
  VITE_ASSET_SERVICE: "${VITE_ASSET_SERVICE}",
  VITE_WAREHOUSE_SERVICE: "${VITE_WAREHOUSE_SERVICE}",
  VITE_SUPPLIER_SERVICE: "${VITE_SUPPLIER_SERVICE}",
  VITE_GRN_SERVICE: "${VITE_GRN_SERVICE}",
};
EOF

exec nginx -g "daemon off;"
