services:
  supplier-db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: supplier_db
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dea-network

  supplier-backend:
    build: ./backend/supplier-service
    ports:
      - "8086:8086"
    depends_on:
      - supplier-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://supplier-db:3306/supplier_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
    networks:
      - dea-network

  supplier-frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - supplier-backend
    networks:
      - dea-network

networks:
  dea-network:
    driver: bridge
