services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8072:8071"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/UserDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ProductDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "3001:3000"
    depends_on:
      - user-service
      - product-service
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge