services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8072:8071"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/userDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/productDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network


  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      VITE_USER_SERVICE: http://localhost:8072
      VITE_PRODUCT_SERVICE: http://localhost:8082
      VITE_PO_SERVICE: http://localhost:8062
    depends_on:
      - user-service
      - product-service
      - maintenance-service
      - purchase-order-service
    networks:
      - inventory-network
  maintenance-service:
    build:
      context: ./maintenance-service
    container_name: maintenance-service
    ports:
      - "8092:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MaintenanceDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
  
  purchase-order-service:
    build:
      context: ./purchase-order-service
    container_name: purchase-order-service
    ports:
      - "8062:8061"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PurchaseOrderDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
networks:
  inventory-network:
    driver: bridge

volumes:
  mysql-data:
