services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-data:/var/lib/mysql
    networks:
      - inventory-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "8072:8071"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/UserDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "8082:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ProductDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network


  frontend:
    build:
      context: ../frontend
    container_name: frontend
    ports:
      - "3001:3000"
    environment:
      VITE_USER_SERVICE: http://localhost:8072
      VITE_PRODUCT_SERVICE: http://localhost:8082
      VITE_PO_SERVICE: http://localhost:8062
      VITE_MAINTENANCE_SERVICE: http://localhost:8092
      VITE_COMPANY_SERVICE: http://localhost:8022
      VITE_STOCK_SERVICE: http://localhost:8042
      VITE_STOCK_TRANSFER_SERVICE: http://localhost:8052
      VITE_ASSET_SERVICE: http://localhost:8012
      VITE_WAREHOUSE_SERVICE: http://localhost:9012
      VITE_SUPPLIER_SERVICE: http://localhost:9022
      VITE_GRN_SERVICE: http://localhost:8032
    depends_on:
      - user-service
      - product-service
      - maintenance-service
      - purchase-order-service
      - company-service
      - stock-service
      - stock-transfer-service
      - asset-service
      - warehouse-service
      - supplier-service
      - grn-service
    networks:
      - inventory-network

  maintenance-service:
    build:
      context: ./maintenance-service
    container_name: maintenance-service
    ports:
      - "8092:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/MaintenanceDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
  
  purchase-order-service:
    build:
      context: ./purchase-order-service
    container_name: purchase-order-service
    ports:
      - "8062:8061"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/PurchaseOrderDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
  
  company-service:
    build:
      context: ./company-service
    container_name: company-service
    ports:
      - "8022:8021"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/CompanyDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8

    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network
  
  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    ports:
      - "8042:8041"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/StockDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  stock-transfer-service:
    build:
      context: ./stock-transfer-service
    container_name: stock-transfer-service
    ports:
      - "8052:8051"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/StockTransferDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  asset-service:
    build:
      context: ./asset-service
    container_name: asset-service
    ports:
      - "8012:8011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/AssetDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  warehouse-service:
    build:
      context: ./warehouse-service
    container_name: warehouse-service
    ports:
      - "9012:9011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/WarehouseDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  supplier-service:
    build:
      context: ./supplier-service
    container_name: supplier-service
    ports:
      - "9022:9021"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/SupplierDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
      SERVICES_PRODUCT_URL: http://product-service:8081
      SERVICES_PURCHASE_ORDER_URL: http://purchase-order-service:8061
      SERVICES_GRN_URL: http://grn-service:8031
      SERVICES_COMPANY_URL: http://company-service:8021
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

  grn-service:
    build:
      context: ./grn-service
    container_name: grn-service
    ports:
      - "8032:8031"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/GrnDB
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - inventory-network

networks:
  inventory-network:
    driver: bridge

volumes:
  mysql-data:
