spring:
  application:
    name: warehouse-service

# external microservice URLs (can be overridden by environment variables)
services:
  purchase-order:
    url: http://localhost:8088
  stock-transfer:
    url: http://localhost:8085
  grn:
    url: http://localhost:8089
  stock:
    url: http://localhost:8090
  company:
    url: http://localhost:8082
