package inventorymanagement.grn_service.entity;

import inventorymanagement.grn_service.enums.GrnStatus;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/*Entity representing the header (summary) of a GRN
This table stores high-level information about the GRN such as:
Company, Warehouse,
Supplier and Purchase Order
Total amounts
Status
Audit information (created / modified details)

Relationship:One GRN Header can contain multiple GRN Detail records
 */

@Entity
@Table(name = "grn_header")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GrnHeader {

    //Primary key of GRN header
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    //Company identifier
    private Long companyId;
    //Warehouse identifier
    private Long warehouseId;
    //Supplier identifier
    private Long supplierId;

    //Associated Purchase Order number
    @Column(nullable = false)
    private String poNumber;

    //Unique GRN number generated by the system
    @Column(nullable = false, unique = true)
    private String grnNumber;

    //Total gross amount (sum of all item gross amounts)
    @Column(precision = 18, scale = 2)
    private BigDecimal totalGrossAmount;

    //Total discount amount
    @Column(precision = 18, scale = 2)
    private BigDecimal totalDiscountAmount;

    //Total net amount (gross - discount)
    @Column(precision = 18, scale = 2)
    private BigDecimal totalNetAmount;

    //Date goods were received
    private LocalDate date;

    //Current status of the GRN, ex: completed, cancelled
    @Enumerated(EnumType.STRING)
    private GrnStatus status;

    //User who created the GRN
    private String createdBy;
    //Creation timestamp
    private LocalDateTime createdDate;

    //User who last modified the GRN
    private String modifiedBy;
    //Last modification timestamp.
    private LocalDateTime modifiedDate;

    // One-to-Many relationship with GRN Detail,
    // Cascade ensures details are saved/deleted with header,
    // Orphan removal ensures removed items are deleted from DB
    @OneToMany(mappedBy = "header", cascade = CascadeType.ALL, orphanRemoval = true)
    @Builder.Default
    private List<GrnDetail> details = new ArrayList<>();
}
