spring:
  application:
    name: stock-service

  datasource:
    url: jdbc:mysql://localhost:3306/StockServiceDB
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8031

jwt:
  secret: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
