/*
 * AddMaintenanceRequestDto
 *
 * This DTO (Data Transfer Object) is used to receive data from the client
 * when creating a new Maintenance record.
 *
 * API Usage:
 * - Triggered when client calls:
 *   POST /api/v1/maintenances
 *
 * Purpose:
 * - Transfers maintenance data from the client layer (Frontend/Postman)
 *   to the Controller and Service layer.
 * - Prevents exposing the Maintenance entity directly.
 *
 * Included Fields:
 * - maintenanceNumber
 * - companyId
 * - warehouseId
 * - assetId
 * - date
 * - cost
 * - description
 * - statusId
 *
 * Excluded Fields:
 * - id (auto-generated by database)
 * - createdDate (system-managed)
 * - modifiedDate (system-managed)
 * - createdBy / modifiedBy (system-managed)
 *
 * Architecture:
 * - Helps maintain clean separation between API layer and database layer.
 * - Supports microservice design by transferring only required data.
 */


package inventorymanagement.maintenance_service.dto;

import jakarta.validation.constraints.*;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/*
 * When called POST /api/v1/maintenances
 * Used to receive data from client when creating a new Maintenance record.
 * Does not include system-managed fields like id, createdDate, modifiedDate.
 */
public class AddMaintenanceRequestDto {

    @NotBlank(message = "Maintenance number is required")
    private String maintenanceNumber;

    @NotNull(message = "Company ID is required")
    private Integer companyId;

    @NotNull(message = "Warehouse ID is required")
    private Integer warehouseId;

    @NotNull(message = "Asset ID is required")
    private Integer assetId;

    @NotNull(message = "Date is required")
    private LocalDateTime date;

    @NotNull(message = "Cost is required")
    @Positive(message = "Cost must be greater than 0")
    private BigDecimal cost;

    @Size(max = 255, message = "Description cannot exceed 255 characters")
    private String description;

    @NotNull(message = "Status ID is required")
    private Integer statusId;

    public AddMaintenanceRequestDto() {
    }

    public AddMaintenanceRequestDto(String maintenanceNumber,
                                    Integer companyId,
                                    Integer warehouseId,
                                    Integer assetId,
                                    LocalDateTime date,
                                    BigDecimal cost,
                                    String description,
                                    Integer statusId) {
        this.maintenanceNumber = maintenanceNumber;
        this.companyId = companyId;
        this.warehouseId = warehouseId;
        this.assetId = assetId;
        this.date = date;
        this.cost = cost;
        this.description = description;
        this.statusId = statusId;
    }

    public String getMaintenanceNumber() {
        return maintenanceNumber;
    }

    public void setMaintenanceNumber(String maintenanceNumber) {
        this.maintenanceNumber = maintenanceNumber;
    }

    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public Integer getWarehouseId() {
        return warehouseId;
    }

    public void setWarehouseId(Integer warehouseId) {
        this.warehouseId = warehouseId;
    }

    public Integer getAssetId() {
        return assetId;
    }

    public void setAssetId(Integer assetId) {
        this.assetId = assetId;
    }

    public LocalDateTime getDate() {
        return date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public String getDescription() {
        return description;
    }

    public Integer getStatusId() {
        return statusId;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
}