package inventorymanagement.grn_service.dto.response;

import inventorymanagement.grn_service.enums.GrnStatus;
import lombok.*;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

/* Response DTO representing a complete GRN

This object is returned to the client when:
Creating a GRN,
Retrieving a GRN by number,
Filtering GRNs,
Updating or Cancelling a GRN

It contains header-level information and a list of item-level details
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class GrnResponse {

    //Unique GRN number generated by the system
    private String grnNumber;
    //Associated Purchase Order number
    private String poNumber;
    //Company identifier
    private Long companyId;
    //Warehouse identifier
    private Long warehouseId;
    //Supplier identifier
    private Long supplierId;
    //Date when goods were received
    private LocalDate date;
    //Current status of the GRN (eg: Completed, Canceled)
    private GrnStatus status;

    //Total gross amount (sum of all item gross amounts)
    private BigDecimal totalGrossAmount;
    //Total discount amount (sum of all item discounts)
    private BigDecimal totalDiscountAmount;
    //Total net amount (gross - discount)
    private BigDecimal totalNetAmount;

    //List of item level details for this GRN
    private List<GrnItemResponse> items;
}