spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/ProductDB
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  port: 8071

jwt:
  secret: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
