spring:
  application:
    name: purchase-order-service
  datasource:
    url: jdbc:mysql://localhost:3306/PurchaseOrderDB
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8061

jwt:
  secret: a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8
