# Application Name
spring.application.name=maintenance-service

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/maintenance_db
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
#spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Server Port
server.port=8092

# Key
jwt.secret=a8F3kLm9PqR2sT7uVxY4zB6nM1cD5eH8